dependencies:
  battery_plus: ^5.0.3
  connectivity_plus:
    git:
      path: packages/connectivity_plus/connectivity_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  crypto: ^3.0.2
  crypton: ^2.1.0
  csslib: ^1.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.4.1
  easy_refresh: ^3.4.0
  extended_image: ^8.2.0
  file_selector:
    git:
      path: packages/file_selector/file_selector
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_smart_dialog: ^4.9.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_swiper_view: ^1.1.8
  flutter_widget_from_html_core: ^0.14.11
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  image_gallery_saver: ^2.0.3
  intl: any
  logger: ^2.0.2+1
  lottie: ^3.0.0
  multi_split_view: ^2.4.0
  package_info_plus:
    git:
      path: packages/package_info_plus/package_info_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  path_provider: ^1.1.0 
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  preload_page_view: ^0.2.0
  protobuf: ^2.1.0
  remixicon: ^1.0.0
  scrollable_positioned_list: ^0.3.8
  share_plus:
    git:
      path: packages/share_plus/share_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  tab_indicator_styler: ^2.0.0
  universal_html: ^2.2.4
  url_launcher:
    git:
      path: packages/url_launcher/url_launcher
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  windows_single_instance: ^1.0.1
description: 动漫之家X
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  msix: ^3.9.1
environment:
  sdk: '>=2.17.3 <4.0.0'
flutter:
  assets:
  - assets/lotties/
  - assets/images/
  - assets/statement.txt
  uses-material-design: true
name: flutter_dmzj
publish_to: none
version: 2.1.1+20101
dependency_overrides:
  path_provider: 
    git:
      path: packages/path_provider/path_provider
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      version: ^1.1.0 
